#!/usr/bin/env bash
set -ex

# Nix on Cygwin install script
# Requires Cygwin with wget

NIXPKGS_VERSION="nixos-18.09" # 19.03 or never fails with "infinite recursion"
NIX_VERSION="2.2.2"
EDITLINE_VERSION="1.16.0"
BROTLI_VERSION="1.0.7"

# apt-cyg
wget https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg
chmod +x apt-cyg
mv apt-cyg /usr/local/bin

# dependencies
apt-cyg install curl wget git patch gcc-core gcc-g++ libtool automake autoconf make cmake patch libboost-devel openssl-devel libbz2-devel libsqlite3-devel libcurl-devel liblzma-devel libsodium-devel

# PKG_CONFIG_PATH
export PKG_CONFIG_PATH="/lib/pkgconfig:/usr/local/lib/pkgconfig"

# brotli
wget https://github.com/google/brotli/archive/v$BROTLI_VERSION.tar.gz
tar xf v$BROTLI_VERSION.tar.gz
rm v$BROTLI_VERSION.tar.gz
cd brotli-$BROTLI_VERSION
mkdir out && cd out
# apt-cyg install dos2unix
# dos2unix.exe ../configure-cmake
../configure-cmake
make
make install
cd ../..
rm -rf brotli-$BROTLI_VERSION

# editline
wget https://github.com/troglobit/editline/releases/download/$EDITLINE_VERSION/editline-$EDITLINE_VERSION.tar.xz
tar xf editline-$EDITLINE_VERSION.tar.xz
rm editline-$EDITLINE_VERSION.tar.gz
cd editline-$EDITLINE_VERSION
./configure
make LDFLAGS=-no-undefined all
make install
cd ..
rm -r editline-$EDITLINE_VERSION

# nix
wget https://nixos.org/releases/nix/nix-$NIX_VERSION/nix-$NIX_VERSION.tar.xz
tar xf nix-$NIX_VERSION.tar.xz
rm nix-$NIX_VERSION.tar.xz
cd nix-$NIX_VERSION/
./bootstrap.sh
./configure
make install
source scripts/nix-profile.sh
mkdir -p /etc/nix
cp scripts/nix-profile.sh /etc/nix/
cd ..
rm -r nix-$NIX_VERSION
prof="source /etc/nix/nix-profile.sh"
grep -qxF $prof ~/.profile || echo $prof >> ~/.profile
nix-channel --add https://nixos.org/channels/$NIXPKGS_VERSION nixpkgs
nix-channel --update

# DONE
echo "Install finished!"
echo "Please execute:"
echo "source ~/.profile"
